language: node_js
node_js: node
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  - sleep 2
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: "allsum"
  on:
    branch: master
