branches:
  only:
    - master
language: node_js
node_js: node
services:
  - mongodb
before_install:
  - npm install -g npm
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: "allsum"
  on:
    branch: master
