const express = require("express");
const mongoose = require("mongoose");

const path = require("path");
const bodyParser = require("body-parser");
const keys = require("./config/keys");

require("./models/User");
require("./models/Song");

mongoose.connect(keys.mongoURI, {
  useNewUrlParser: true,
  useFindAndModify: false
});

const app = express();

app.use(bodyParser.json());

app.get("/test", (req, res) => {
  res.send({ hi: "there" });
});

//route handler
require("./routes/songRoutes")(app);
require("./routes/userRoutes")(app);

//grab index.html generated by build
if (process.env.NODE_ENV === "production") {
  app.use(express.static("client/build"));

  app.get("*", (req, res) => {
    res.sendFile(path.resolve(__dirname, "client", "build", "index.html"));
  });
}
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(PORT);
});
